# -*- coding: utf-8 -*-
"""
Extra Russian -> English replacements covering body content of the 25 remaining
Libermall ID landing pages. Each tuple is anchored with enough context
(>tag<, full attribute value, full sentence) so .replace() is safe.

Brand: Libermall (capital L). Ecosystem mentions: dex.libermall.com,
pay.libermall.com (where contextually relevant).
"""

EXTRA_REPLACEMENTS = [
    # ── 404.html ──
    ('content="Страница не найдена. Вернитесь на главную Libermall ID.">',
     'content="Page not found. Return to the Libermall ID home page.">'),
    ('>Страница не найдена</h1>', '>Page not found</h1>'),
    ('You may have followed a stale link. Go to the home page or документацию.',
     'You may have followed a stale link. Go to the home page or the documentation.'),

    # ── login.html ──
    ('content="Войдите в Libermall ID — Telegram, TON Connect, Google, Apple или email magic-link.">',
     'content="Sign in to Libermall ID — Telegram, TON Connect, Google, Apple or email magic link.">'),
    ('>Войдите в Libermall ID одним кликом</p>',
     '>Sign in to Libermall ID with one click</p>'),
    ('>Продолжая, вы соглашаетесь с <a href="/terms.html">Условиями</a> и <a href="/privacy.html">Политикой&nbsp;приватности</a></p>',
     '>By continuing you agree to the <a href="/terms.html">Terms</a> and <a href="/privacy.html">Privacy&nbsp;Policy</a></p>'),
    ('>Нет аккаунта? <a href="/signup.html">Create</a></p>',
     '>No account yet? <a href="/signup.html">Create</a></p>'),

    # ── signup.html ──
    ('<title>Создать аккаунт — Libermall ID</title>',
     '<title>Create account — Libermall ID</title>'),
    ('content="Создайте аккаунт Libermall ID за минуту. Выберите способ входа.">',
     'content="Create a Libermall ID account in a minute. Choose your sign-in method.">'),
    ('content="Создать аккаунт — Libermall ID">',
     'content="Create account — Libermall ID">'),
    ('"name": "Создать аккаунт",', '"name": "Create account",'),
    ('"position": 2, "name": "Создать аккаунт", "item":',
     '"position": 2, "name": "Create account", "item":'),
    ('>Создайте аккаунт</h1>', '>Create your account</h1>'),
    ('>Выберите способ регистрации</p>', '>Choose how to sign up</p>'),
    ('>в 1 тап</span>', '>in 1 tap</span>'),
    ('>Создавая аккаунт, вы соглашаетесь с <a href="/terms.html">Условиями</a> и <a href="/privacy.html">Политикой</a></p>',
     '>By creating an account you agree to the <a href="/terms.html">Terms</a> and <a href="/privacy.html">Privacy Policy</a></p>'),
    ('>Уже есть аккаунт? <a href="/login.html">Sign in</a></p>',
     '>Already have an account? <a href="/login.html">Sign in</a></p>'),

    # ── signup-username.html ──
    ('<title>Выберите username — Libermall ID</title>',
     '<title>Pick a username — Libermall ID</title>'),
    ('content="Выберите username — Libermall ID">',
     'content="Pick a username — Libermall ID">'),
    ('>Выберите username</h1>', '>Pick a username</h1>'),
    ('>Уникальное имя в экосистеме Libermall</p>',
     '>Your unique handle across the Libermall ecosystem</p>'),
    ('>4-30 символов</li>', '>4–30 characters</li>'),
    ('>Буквы, цифры, точки и нижние подчёркивания</li>',
     '>Letters, digits, dots and underscores</li>'),
    ('>Должен быть уникальным</li>', '>Must be unique</li>'),
    ('>Назад</a>', '>Back</a>'),
    ('>Продолжить →</a>', '>Continue →</a>'),

    # ── signup-profile.html ──
    ('>Завершите профиль</h1>', '>Finish your profile</h1>'),
    ('>Добавьте аватар и имя</p>', '>Add an avatar and a name</p>'),
    ('>Кликните чтобы загрузить</div>', '>Click to upload</div>'),
    ('>Заполнить позже — <a href="/dashboard.html">пропустить</a></p>',
     '>Fill in later — <a href="/dashboard.html">skip</a></p>'),

    # ── blog.html ──
    ('<p>Готовый Socialite provider + middleware. Telegram-вход на каждом проекте.</p>',
     '<p>A ready-made Socialite provider + middleware. Telegram sign-in across every project.</p>'),
    ('>5 мин чтения · 2026-05-24</div>', '>5 min read · 2026-05-24</div>'),
    ('<p>Криптостойкость vs производительность. Разбор decision tree.</p>',
     '<p>Cryptographic strength vs. performance. A look at the decision tree.</p>'),
    ('>8 мин чтения · 2026-05-23</div>', '>8 min read · 2026-05-23</div>'),
    ('<p>Как мы реализовали TON Connect proof через Casdoor custom adapter.</p>',
     '<p>How we implemented TON Connect proof via a Casdoor custom adapter.</p>'),
    ('>12 мин чтения · 2026-05-22</div>', '>12 min read · 2026-05-22</div>'),
    ('<h3>Что такое Libermall Passport (и почему это не Telegram Passport 2.0)</h3>',
     '<h3>What Libermall Passport is (and why it is not Telegram Passport 2.0)</h3>'),
    ('<p>Концепция Phase 6: KYC под cryptographic seal.</p>',
     '<p>Phase 6 concept: KYC under a cryptographic seal.</p>'),
    ('>6 мин чтения · 2026-05-21</div>', '>6 min read · 2026-05-21</div>'),
    ('<h3>Libermall Mail на TON Storage</h3>',
     '<h3>Libermall Mail on TON Storage</h3>'),
    ('<p>Why we&apos;re building decentralized email on TON. Технические вызовы.</p>',
     '<p>Why we&apos;re building decentralized email on TON. The technical challenges.</p>'),
    ('>10 мин чтения · 2026-05-20</div>', '>10 min read · 2026-05-20</div>'),
    ('<p>Как замена email/password на Telegram login увеличила конверсию.</p>',
     '<p>How replacing email/password with Telegram login lifted conversion.</p>'),
    ('>4 мин чтения · 2026-05-19</div>', '>4 min read · 2026-05-19</div>'),

    # ── changelog.html ──
    ('content="История обновлений Libermall ID. Каждый релиз с changelog\'ом.">',
     'content="Libermall ID release history. Every release with its changelog.">'),
    ('>Личный кабинет /dashboard со списком сессий и подключённых аккаунтов</li>',
     '>Personal /dashboard with a list of sessions and connected accounts</li>'),
    ('>5 методов входа: Telegram / TON Connect / Google / Apple / Email magic-link</li>',
     '>5 sign-in methods: Telegram / TON Connect / Google / Apple / Email magic link</li>'),
    ('>Custom auth flow — 3 шага регистрации</li>',
     '>Custom auth flow — 3-step registration</li>'),
    ('>Mobile 6-digit confirmation для входа на новых устройствах</li>',
     '>Mobile 6-digit confirmation for sign-in on new devices</li>'),
    ('>12 новых страниц: status, blog, pricing, compare, use-cases, customers, api/playground, docs/quickstart, legal/dpa, legal/sla, security, changelog</li>',
     '>12 new pages: status, blog, pricing, compare, use-cases, customers, api/playground, docs/quickstart, legal/dpa, legal/sla, security, changelog</li>'),
    ('>Mini App для @LibermallIDbot — профиль, продукты, безопасность</li>',
     '>Mini App for @LibermallIDbot — profile, products, security</li>'),
    ('>Брендирование Casdoor /login (logo, primary color, signinHtml)</li>',
     '>Casdoor /login branding (logo, primary color, signinHtml)</li>'),
    ('>Footer соцсети: GitHub, X, VK, Instagram, Telegram</li>',
     '>Footer social links: GitHub, X, VK, Instagram, Telegram</li>'),
    ('>Brand Book v2.0 — палитра, типографика, компоненты</li>',
     '>Brand Book v2.0 — palette, typography, components</li>'),
    ('>Casdoor self-hosted на id.libermall.com</li>',
     '>Casdoor self-hosted on id.libermall.com</li>'),
    ('>Sites.Reviews как первый OAuth-client</li>',
     '>Sites.Reviews as the first OAuth client</li>'),
    ('>JWT RS256 4096-bit cert для подписи токенов</li>',
     '>JWT RS256 4096-bit cert for token signing</li>'),

    # ── compare.html ──
    ('content="Сравнение Libermall ID с Auth0, Clerk, Stytch, Keycloak. Open source, Web3-нативный, бесплатный.">',
     'content="Libermall ID compared to Auth0, Clerk, Stytch, Keycloak. Open source, Web3-native, free.">'),
    ('"name": "Сравнение",', '"name": "Compare",'),
    ('"position": 2, "name": "Сравнение", "item":',
     '"position": 2, "name": "Compare", "item":'),
    ('>Данные основаны на public pricing pages по состоянию на 2026-05. Поправки: <a href="mailto:hello@libermall.com">hello@libermall.com</a></p>',
     '>Data based on public pricing pages as of 2026-05. Corrections: <a href="mailto:hello@libermall.com">hello@libermall.com</a></p>'),
    ('>Готовы попробовать?</h2>', '>Ready to try it?</h2>'),
    ('>Создайте аккаунт за минуту — без банковской карты.</p>',
     '>Create an account in a minute — no credit card required.</p>'),

    # ── customers.html ──
    ('content="Кейсы интеграции Libermall ID в реальные проекты.">',
     'content="Real-world Libermall ID integration case studies.">'),
    ('"name": "Клиенты",', '"name": "Customers",'),
    ('"position": 2, "name": "Клиенты", "item":',
     '"position": 2, "name": "Customers", "item":'),
    ('«Замена самописной auth на Libermall ID сократила drop-off на 78%. Telegram-вход одним тапом — пользователи перестали бросать форму на полпути.»',
     '"Replacing our custom auth with Libermall ID cut drop-off by 78%. One-tap Telegram sign-in stopped people abandoning the form halfway through."'),
    ('<b>Команда Sites.Reviews</b> · Frankfurt, DE',
     '<b>Sites.Reviews team</b> · Frankfurt, DE'),
    ('«TON Connect IdP позволил привязать wallets как identity. Юзер видит свою историю свопов в любом продукте экосистемы.»',
     '"The TON Connect IdP lets us bind wallets as identity. A user sees their swap history across every ecosystem product."'),
    ('<b>Команда Libermall DEX</b>', '<b>Libermall DEX team</b>'),
    ('<div class="stat-lbl">мин до интеграции</div>',
     '<div class="stat-lbl">min to integrate</div>'),
    ('«Cross-product история подписок переехала автоматически. Пользователи Stars в @TonChatAIBot теперь видят балансы Card.»',
     '"Cross-product subscription history migrated automatically. Stars users in @TonChatAIBot now see their Card balance."'),
    ('<b>Команда TonChat AI</b>', '<b>TonChat AI team</b>'),
    ('<div class="stat-lbl">Сбросов паролей</div>',
     '<div class="stat-lbl">Password resets</div>'),
    ('«Запуск Telegram Mini App с встроенной авторизацией через Libermall ID — два дня работы вместо двух недель.»',
     '"Shipping a Telegram Mini App with built-in Libermall ID auth took two days instead of two weeks."'),
    ('<b>Команда Libermall Card</b>', '<b>Libermall Card team</b>'),
    ('<div class="stat-num">2 дня</div>', '<div class="stat-num">2 days</div>'),
    ('>Хотите попасть в этот список?</h2>', '>Want to be featured here?</h2>'),
    ('>Интегрируйте Libermall ID — расскажем вашу историю на этой странице.</p>',
     '>Integrate Libermall ID — we will share your story on this page.</p>'),
    ('>Интегрировать →</a>', '>Integrate →</a>'),

    # ── status.html ──
    ('content="Статус системы Libermall ID: uptime, реальные показатели каждого endpoint.">',
     'content="Libermall ID system status: uptime and live numbers for every endpoint.">'),
    ('"name": "Статус системы",', '"name": "System status",'),
    ('"position": 2, "name": "Статус системы", "item":',
     '"position": 2, "name": "System status", "item":'),
    ('>Telegram Bot Webhook deg.: HTTP 502 (3 минуты)</div>',
     '>Telegram Bot Webhook deg.: HTTP 502 (3 minutes)</div>'),

    # ── security.html ──
    ('"name": "Безопасность",', '"name": "Security",'),
    ('"position": 2, "name": "Безопасность", "item":',
     '"position": 2, "name": "Security", "item":'),
    ('<div class="desc">4096-bit подпись, JWKS rotation каждые 90 дней</div>',
     '<div class="desc">4096-bit signature, JWKS rotation every 90 days</div>'),
    ('<div class="desc">12-month retention, GDPR-export по запросу</div>',
     '<div class="desc">12-month retention, GDPR export on request</div>'),
    ('<div class="desc">Per-IP / per-account / per-token защита от brute-force</div>',
     '<div class="desc">Per-IP / per-account / per-token brute-force protection</div>'),
    ('<div class="desc">Список активных устройств + remote revoke в один клик</div>',
     '<div class="desc">List of active devices + one-click remote revoke</div>'),
    ('<div class="desc">Casdoor core + наш UI публично на github.com/LiberMall</div>',
     '<div class="desc">Casdoor core + our UI public on github.com/LiberMall</div>'),
    ('<div class="desc">Изолированный VPS Frankfurt, открыты только 22/80/443</div>',
     '<div class="desc">Isolated Frankfurt VPS, only ports 22/80/443 open</div>'),
    ('>Нашли уязвимость? Сообщите на <a href="mailto:security@libermall.com">security@libermall.com</a>. Bug bounty rewards $50–$5000 в зависимости от severity. Мы признаём researchers публично (с согласия).</p>',
     '>Found a vulnerability? Report it to <a href="mailto:security@libermall.com">security@libermall.com</a>. Bug bounty rewards $50–$5000 depending on severity. We credit researchers publicly (with consent).</p>'),
    ('>GDPR — compliant сейчас (export/delete на запрос за 30 дней)</li>',
     '>GDPR — compliant today (export/delete on request within 30 days)</li>'),

    # ── pricing.html ──
    ('content="Прозрачные тарифы Libermall ID. Бесплатно для пользователей, free tier до 10K MAU для разработчиков.">',
     'content="Transparent Libermall ID pricing. Free for end users, free tier up to 10K MAU for developers.">'),
    ('"name": "Тарифы",', '"name": "Pricing",'),
    ('"position": 2, "name": "Тарифы", "item":',
     '"position": 2, "name": "Pricing", "item":'),
    ('>Бесплатно для всех пользователей навсегда. Платим только за enterprise-фичи.</p>',
     '>Free forever for end users. You only pay for enterprise features.</p>'),
    ('Все 5 методов входа</li>', 'All 5 sign-in methods</li>'),
    ('До 10K MAU</li>', 'Up to 10K MAU</li>'),
    ('>Начать бесплатно</a>', '>Start free</a>'),
    ('<div class="price">$99 <small>/ месяц</small></div>',
     '<div class="price">$99 <small>/ month</small></div>'),
    ('<p style="color:var(--muted);font-size:13px;margin:0;">До 100K MAU. Email + Slack support.</p>',
     '<p style="color:var(--muted);font-size:13px;margin:0;">Up to 100K MAU. Email + Slack support.</p>'),
    ('Всё из Free</li>', 'Everything in Free</li>'),
    ('До 100K MAU</li>', 'Up to 100K MAU</li>'),
    ('Кастомный consent screen</li>', 'Custom consent screen</li>'),
    ('DPA + SLA контракты</li>', 'DPA + SLA contracts</li>'),
    ('>Все тарифы включают: бесплатный SSL, OIDC/OAuth/SAML, 99.9% uptime SLA. <a href="/compare.html">Сравнить с конкурентами →</a></p>',
     '>All plans include: free SSL, OIDC/OAuth/SAML, 99.9% uptime SLA. <a href="/compare.html">Compare with competitors →</a></p>'),

    # ── api-playground.html ──
    ('content="Интерактивный API explorer для Libermall ID. Попробуйте OIDC endpoints в реальном времени.">',
     'content="Interactive API explorer for Libermall ID. Try OIDC endpoints in real time.">'),
    ('>Discovery doc — все endpoints</div>',
     '>Discovery doc — every endpoint</div>'),
    ('>Public keys для верификации JWT</div>',
     '>Public keys for JWT verification</div>'),
    ('>Authorization endpoint — редирект юзера</div>',
     '>Authorization endpoint — user redirect</div>'),
    ('>UserInfo — claims с Bearer токеном</div>',
     '>UserInfo — claims with a Bearer token</div>'),

    # ── developers.html ──
    ('content="Документация Libermall ID для разработчиков: OpenID Connect, OAuth 2.0, SAML, SDK для Laravel, Next.js, Node, Python, curl.">',
     'content="Libermall ID developer documentation: OpenID Connect, OAuth 2.0, SAML, SDKs for Laravel, Next.js, Node, Python, curl.">'),
    ('>Подключите Libermall ID<br><span class="accent">за 5 минут</span></h1>',
     '>Plug in Libermall ID<br><span class="accent">in 5 minutes</span></h1>'),
    ('>Стандартный OpenID Connect — никакого vendor lock-in. Готовые SDK для популярных стеков.</p>',
     '>Standard OpenID Connect — no vendor lock-in. Ready-made SDKs for popular stacks.</p>'),
    ('>Все endpoint\'ы находятся под <code',
     '>All endpoints live under <code'),
    ('User clicks "Войти через Libermall ID"',
     'User clicks "Sign in with Libermall ID"'),
    ('Redirect к <span class="c-str">',
     'Redirect to <span class="c-str">'),
    ('Casdoor показывает форму, юзер логинится (Telegram, TON, email, Apple, Google)',
     'Casdoor renders the form, the user signs in (Telegram, TON, email, Apple, Google)'),
    ('Casdoor редиректит обратно на <span class="c-str">',
     'Casdoor redirects back to <span class="c-str">'),
    ('Ваш сервер обменивает code на access_token через POST <span class="c-str">',
     'Your server exchanges the code for an access_token via POST <span class="c-str">'),
    ('GET <span class="c-str">/api/userinfo</span> с Bearer токеном → claims</pre>',
     'GET <span class="c-str">/api/userinfo</span> with the Bearer token → claims</pre>'),
    ('>Готовые примеры под популярные стеки</h2>',
     '>Ready-made examples for popular stacks</h2>'),
    ('>Что возвращает id_token</h2>', '>What id_token returns</h2>'),
    ('<tr><th>Scope</th><th>Что включает</th></tr>',
     '<tr><th>Scope</th><th>Includes</th></tr>'),
    ('<td>Обязательный для OIDC. Возвращает <code>sub</code>.</td>',
     '<td>Required for OIDC. Returns <code>sub</code>.</td>'),
    ('<td>Массив привязанных TON-кошельков с верификацией</td>',
     '<td>Array of linked TON wallets with verification</td>'),
    ('<td>refresh_token для долгих сессий</td>',
     '<td>refresh_token for long-lived sessions</td>'),
    ('<td>Доступ к Quest-API для Libermall Card achievements</td>',
     '<td>Access to the Quest API for Libermall Card achievements</td>'),
    ('>Получите client_id за сутки</h2>', '>Get a client_id within 24 hours</h2>'),
    ('>Регистрация OAuth-приложений пока ручная. Напишите на hello@libermall.com — вышлем credentials.</p>',
     '>OAuth app registration is manual for now. Email hello@libermall.com and we will send credentials.</p>'),
    ('<h3>1. Пришлите info</h3>', '<h3>1. Send your info</h3>'),
    ('<p>Название сервиса, URL, список redirect_uri, нужные scopes.</p>',
     '<p>Service name, URL, list of redirect_uri, required scopes.</p>'),
    ('<h3>2. Получите ключи</h3>', '<h3>2. Receive the keys</h3>'),
    ('<p>client_id + client_secret в течение 24 часов.</p>',
     '<p>client_id + client_secret within 24 hours.</p>'),
    ('<h3>3. Готово</h3>', '<h3>3. Done</h3>'),
    ('<p>Интегрируйте за 5 минут — кнопка «Войти через Libermall ID» работает.</p>',
     '<p>Integrate in 5 minutes — the "Sign in with Libermall ID" button just works.</p>'),
    ('>Готовы интегрировать?</h2>', '>Ready to integrate?</h2>'),
    ('>Получите client_id, добавьте кнопку, и 7000+ пользователей экосистемы войдут одним кликом.</p>',
     '>Get a client_id, add the button, and 7,000+ ecosystem users will sign in with a single click.</p>'),
    ('>Подробнее об интеграции</a>',
     '>More about integration</a>'),

    # ── docs-quickstart.html ──
    ('content="5-минутный quickstart для интеграции Libermall ID. Готовые snippet\'ы.">',
     'content="5-minute quickstart for integrating Libermall ID. Copy-paste snippets.">'),
    ('>От нуля до работающего «Войти через Libermall ID» на вашем сайте.</p>',
     '>From zero to a working "Sign in with Libermall ID" button on your site.</p>'),
    ('>1. Получите client_id</a>', '>1. Get a client_id</a>'),
    ('>2. Установите SDK</a>', '>2. Install the SDK</a>'),
    ('>3. Настройте redirect</a>', '>3. Configure the redirect</a>'),
    ('>4. Добавьте кнопку</a>', '>4. Add the button</a>'),
    ('>5. Обработайте callback</a>', '>5. Handle the callback</a>'),
    ('>1. Получите client_id</h2>', '>1. Get a client_id</h2>'),
    ('<p>Напишите на <a href="mailto:hello@libermall.com?subject=Libermall%20ID%20client%20request">hello@libermall.com</a> с информацией:</p>',
     '<p>Email <a href="mailto:hello@libermall.com?subject=Libermall%20ID%20client%20request">hello@libermall.com</a> with:</p>'),
    ('>Название и URL сервиса</li>', '>Service name and URL</li>'),
    ('>Redirect URIs (одна или несколько)</li>',
     '>Redirect URIs (one or more)</li>'),
    ('>Нужные scopes: <code>openid profile email</code> минимум</li>',
     '>Required scopes: <code>openid profile email</code> at minimum</li>'),
    ('<p>Получите <code>client_id</code> и <code>client_secret</code> в течение суток.</p>',
     '<p>You will receive <code>client_id</code> and <code>client_secret</code> within 24 hours.</p>'),
    ('>2. Установите SDK</h2>', '>2. Install the SDK</h2>'),
    ('# или для Laravel', '# or for Laravel'),
    ('# или для Python', '# or for Python'),
    ('>3. Настройте redirect</h2>', '>3. Configure the redirect</h2>'),
    ('<p>В вашем приложении настройте OAuth-клиент с этими значениями:</p>',
     '<p>Configure an OAuth client in your application with these values:</p>'),
    ('LIBERMALL_ID_CLIENT_ID=<полученный_id>',
     'LIBERMALL_ID_CLIENT_ID=<your_id>'),
    ('LIBERMALL_ID_CLIENT_SECRET=<полученный_secret>',
     'LIBERMALL_ID_CLIENT_SECRET=<your_secret>'),
    ('>4. Добавьте кнопку</h2>', '>4. Add the button</h2>'),
    ('<p>Готовый snippet — копируйте как есть:</p>',
     '<p>Ready-made snippet — copy as is:</p>'),
    ('  Войти через Libermall ID', '  Sign in with Libermall ID'),
    ('>5. Обработайте callback</h2>', '>5. Handle the callback</h2>'),
    ('<p>Пример для Express:</p>', '<p>Express example:</p>'),
    ('<h2>Готово 🎉</h2>', '<h2>Done 🎉</h2>'),
    ('<p>Пользователи могут входить через Telegram, TON Connect, Google, Apple или Email одной кнопкой. Подробности — в <a href="/developers.html">полной документации</a>.</p>',
     '<p>Users can sign in via Telegram, TON Connect, Google, Apple or Email with one button. Details in the <a href="/developers.html">full documentation</a>.</p>'),
    ('<h2 style="font-size:1.4rem;">Нужна помощь?</h2>',
     '<h2 style="font-size:1.4rem;">Need help?</h2>'),
    ('<p>Опишите ваш стек на <a href="mailto:hello@libermall.com">hello@libermall.com</a> — поможем с интеграцией.</p>',
     '<p>Describe your stack at <a href="mailto:hello@libermall.com">hello@libermall.com</a> — we will help with the integration.</p>'),

    # ── index.html ──
    ('<title>Libermall ID — Один аккаунт для всей экосистемы</title>',
     '<title>Libermall ID — One account for the entire ecosystem</title>'),
    ('content="Войдите через Telegram, TON Connect, Apple, Google или email — получите доступ ко всей экосистеме Libermall: Sites.Reviews, TonChat AI, TON.CEO, DEX, Card, Marketplace.">',
     'content="Sign in via Telegram, TON Connect, Apple, Google or email — and unlock the whole Libermall ecosystem: Sites.Reviews, TonChat AI, TON.CEO, DEX (dex.libermall.com), Card, PayLibermall (pay.libermall.com), Marketplace.">'),
    ('content="Libermall ID — единый аккаунт для всей экосистемы">',
     'content="Libermall ID — one account for the entire ecosystem">'),
    ('content="Войдите через Telegram или TON Connect. OpenID Connect, OAuth 2.0, open source.">',
     'content="Sign in with Telegram or TON Connect. OpenID Connect, OAuth 2.0, open source.">'),
    ('{ "@type": "Question", "name": "Сколько стоит Libermall ID?", "acceptedAnswer": { "@type": "Answer", "text": "Бесплатно навсегда для пользователей. Для разработчиков — бесплатный tier OIDC до 10K MAU, дальше — по согласованию." } },',
     '{ "@type": "Question", "name": "How much does Libermall ID cost?", "acceptedAnswer": { "@type": "Answer", "text": "Free forever for end users. For developers — a free OIDC tier up to 10K MAU, beyond that on request." } },'),
    ('{ "@type": "Question", "name": "Где хранятся мои данные?", "acceptedAnswer": { "@type": "Answer", "text": "На изолированном VPS в Frankfurt. Профиль и сессии — PostgreSQL, кэш — Redis. Резервные копии шифруются." } },',
     '{ "@type": "Question", "name": "Where is my data stored?", "acceptedAnswer": { "@type": "Answer", "text": "On an isolated VPS in Frankfurt. Profile and sessions in PostgreSQL, cache in Redis. Backups are encrypted." } },'),
    ('{ "@type": "Question", "name": "Что если я потеряю доступ к Telegram?", "acceptedAnswer": { "@type": "Answer", "text": "Привяжите второй способ входа (TON Connect или email) — это резерв. Также можно настроить 2FA recovery codes." } }',
     '{ "@type": "Question", "name": "What if I lose access to Telegram?", "acceptedAnswer": { "@type": "Answer", "text": "Link a second sign-in method (TON Connect or email) as a backup. You can also set up 2FA recovery codes." } }'),
    ('Открыть @LibermallIDbot', 'Open @LibermallIDbot'),
    ('>Вы можете использовать Libermall ID во всех продуктах.</p>',
     '>You can use Libermall ID across every product.</p>'),
    ('<p>Auth core — Casdoor (BSD 3-Clause). Наш UI и бот — MIT на github.com/LiberMall. Кастомные адаптеры для TG и TON — тоже public.</p>',
     '<p>Auth core — Casdoor (BSD 3-Clause). Our UI and bot — MIT on github.com/LiberMall. The custom TG and TON adapters are public too.</p>'),

    # ── use-cases.html ──
    ('content="Для кого подходит Libermall ID: Web3 dApps, E-commerce, SaaS, мобильные приложения, Telegram Mini Apps.">',
     'content="Who Libermall ID is for: Web3 dApps, e-commerce, SaaS, mobile apps, Telegram Mini Apps.">'),
    ('>Для каких продуктов подходит Libermall ID</h1>',
     '>What products Libermall ID fits</h1>'),
    ('>5 сценариев применения: от dApp до классического SaaS.</p>',
     '>5 use cases — from dApps to classic SaaS.</p>'),
    ('<p>TON Connect login с поддержкой Tonkeeper, MyTonWallet, Tonhub. Юзер подписывает proof — становится identity.</p>',
     '<p>TON Connect login with Tonkeeper, MyTonWallet, Tonhub support. The user signs a proof — it becomes their identity. Powers dex.libermall.com.</p>'),
    ('<p>Один аккаунт для входа на разных площадках экосистемы. Wishlists, история, рейтинг — переносятся.</p>',
     '<p>One account across every storefront in the ecosystem. Wishlists, history, ratings — they carry over.</p>'),
    ('<ul><li>Cross-store checkout</li><li>Quest система</li><li>Reviews привязаны к ID</li></ul>',
     '<ul><li>Cross-store checkout</li><li>Quest system</li><li>Reviews tied to your ID</li></ul>'),
    ('<p>Замените самописную auth на стандартный OIDC. Меньше кода, меньше уязвимостей, выше конверсия.</p>',
     '<p>Swap homegrown auth for standard OIDC. Less code, fewer vulnerabilities, higher conversion.</p>'),
    ('<ul><li>OAuth 2.0 + PKCE</li><li>Готовые SDK</li><li>5 минут до интеграции</li></ul>',
     '<ul><li>OAuth 2.0 + PKCE</li><li>Ready-made SDKs</li><li>5 minutes to integrate</li></ul>'),
    ('<p>Telegram-вход без OAuth-редиректов — нативный flow в Telegram WebApp. Один тап.</p>',
     '<p>Telegram sign-in without OAuth redirects — a native flow inside Telegram WebApp. One tap.</p>'),
    ('<p>Если ваш сервис — Mini App в Telegram, Libermall ID работает нативно: HMAC initData валидируется автоматически.</p>',
     '<p>If your service is a Telegram Mini App, Libermall ID is native: HMAC initData is validated automatically.</p>'),
    ('<ul><li>initData валидация</li><li>Bot API интеграция</li><li>chat_id sync</li></ul>',
     '<ul><li>initData validation</li><li>Bot API integration</li><li>chat_id sync</li></ul>'),
    ('<p>Импорт пользователей через Libermall ID. Кросс-комьюнити репутация — отзывы Sites.Reviews видны в форуме.</p>',
     '<p>Import users via Libermall ID. Cross-community reputation — Sites.Reviews ratings show up in the forum.</p>'),
    ('<ul><li>Reputation API</li><li>Verified badge</li><li>Anti-bot защита</li></ul>',
     '<ul><li>Reputation API</li><li>Verified badge</li><li>Anti-bot protection</li></ul>'),
    ('>Ваш use case не в списке?</h2>',
     '>Your use case is not on the list?</h2>'),
    ('>Напишите — обсудим как Libermall ID решает вашу задачу.</p>',
     '>Email us — we will discuss how Libermall ID solves your case.</p>'),

    # ── integrate.html ──
    ('<title>Интегрировать Libermall ID — за 5 минут</title>',
     '<title>Integrate Libermall ID — in 5 minutes</title>'),
    ('content="Добавьте «Войти через Libermall ID» на свой сайт. Готовый OAuth client, бесплатно до 10K MAU, SDK для популярных стеков.">',
     'content="Add a Sign in with Libermall ID button to your site. Ready-made OAuth client, free up to 10K MAU, SDKs for popular stacks.">'),
    ('content="Интегрировать Libermall ID за 5 минут">',
     'content="Integrate Libermall ID in 5 minutes">'),
    ('content="Интегрировать Libermall ID — за 5 минут">',
     'content="Integrate Libermall ID — in 5 minutes">'),
    ('"name": "Интегрировать",', '"name": "Integrate",'),
    ('"position": 2, "name": "Интегрировать", "item":',
     '"position": 2, "name": "Integrate", "item":'),
    ('>Добавьте кнопку<br><span class="accent">«Войти через Libermall ID»</span></h1>',
     '>Add the<br><span class="accent">"Sign in with Libermall ID"</span> button</h1>'),
    ('>Connect your service to the Libermall ecosystem. Get instant access to 7000+ верифицированных пользователей с привязанными кошельками.</p>',
     '>Connect your service to the Libermall ecosystem. Get instant access to 7,000+ verified users with linked wallets.</p>'),
    ('>Запросить доступ</a>', '>Request access</a>'),
    ('>Что вы получаете</h2>', '>What you get</h2>'),
    ('<h3>+ Конверсия</h3>', '<h3>+ Conversion</h3>'),
    ('<p>Один клик в Telegram вместо формы с email/password/captcha. Конверсия в 3-5× выше типичной.</p>',
     '<p>One click in Telegram instead of an email/password/captcha form. Conversion 3–5× higher than typical.</p>'),
    ('<h3>Готовая аудитория</h3>', '<h3>Built-in audience</h3>'),
    ('<p>7000+ верифицированных пользователей экосистемы Libermall. Они уже знают что такое Libermall ID.</p>',
     '<p>7,000+ verified users of the Libermall ecosystem. They already know what Libermall ID is.</p>'),
    ('<h3>Контекст пользователя</h3>', '<h3>User context</h3>'),
    ('<p>TON-кошельки, отзывы, рейтинг трейдера — переходят с пользователем. Лучше персонализация.</p>',
     '<p>TON wallets, reviews, trader rating — they travel with the user. Better personalization.</p>'),
    ('>3 шага до интеграции</h2>', '>3 steps to integrate</h2>'),
    ('<h3>Запросите OAuth client</h3>', '<h3>Request an OAuth client</h3>'),
    ('<p>Напишите на <a href="mailto:hello@libermall.com">hello@libermall.com</a> — пришлите название, URL, redirect_uri. Получите client_id и client_secret в течение суток.</p>',
     '<p>Email <a href="mailto:hello@libermall.com">hello@libermall.com</a> with your name, URL and redirect_uri. You will get a client_id and client_secret within 24 hours.</p>'),
    ('<h3>Подключите OIDC SDK</h3>', '<h3>Wire up the OIDC SDK</h3>'),
    ('<p>Готовые примеры для Laravel, Next.js, Node, Python в <a href="/developers.html">документации</a>. Стандартный OpenID Connect — работает с любым OIDC-клиентом.</p>',
     '<p>Ready-made examples for Laravel, Next.js, Node, Python in the <a href="/developers.html">documentation</a>. Standard OpenID Connect — works with any OIDC client.</p>'),
    ('<h3>Добавьте кнопку</h3>', '<h3>Add the button</h3>'),
    ('<p>Брендированный snippet HTML/CSS — копируете в <a href="/developers.html#button">developers/button</a>. Юзеры экосистемы войдут одним кликом.</p>',
     '<p>A branded HTML/CSS snippet — copy it from <a href="/developers.html#button">developers/button</a>. Ecosystem users will sign in with a single click.</p>'),
    ('>Кто уже принимает Libermall ID</h2>',
     '>Who already accepts Libermall ID</h2>'),
    ('>6 продуктов экосистемы Libermall и внешние партнёры.</p>',
     '>6 Libermall ecosystem products and external partners — including dex.libermall.com and pay.libermall.com.</p>'),
    ('>Бесплатно до 10K MAU</h2>', '>Free up to 10K MAU</h2>'),
    ('>Стартовый tier для всех. Платно — только при крупных объёмах или enterprise-фичах.</p>',
     '>Starter tier for everyone. Paid only at high volume or for enterprise features.</p>'),
    ('<div class="price">$0 <small>до 10K MAU</small></div>',
     '<div class="price">$0 <small>up to 10K MAU</small></div>'),
    ('<p style="color:var(--muted);font-size:13px;margin:0;">Для пилотов, стартапов, indie-проектов.</p>',
     '<p style="color:var(--muted);font-size:13px;margin:0;">For pilots, startups and indie projects.</p>'),
    ('>Запросить</a>', '>Request</a>'),
    ('>Готовы добавить кнопку?</h2>', '>Ready to add the button?</h2>'),
    ('<p>Напишите команде Libermall — поможем с интеграцией.</p>',
     '<p>Email the Libermall team — we will help with the integration.</p>'),

    # ── dashboard.html ──
    ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="8" r="4"/><path d="M4 21v-1a8 8 0 0 1 16 0v1"/></svg>Профиль</a>',
     '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="8" r="4"/><path d="M4 21v-1a8 8 0 0 1 16 0v1"/></svg>Profile</a>'),
    ('<path d="M18 12a2 2 0 0 0 0 4h4v-4z"/></svg>Кошельки</a>',
     '<path d="M18 12a2 2 0 0 0 0 4h4v-4z"/></svg>Wallets</a>'),
    ('<line x1="12" y1="17" x2="12" y2="21"/></svg>Сессии</a>',
     '<line x1="12" y1="17" x2="12" y2="21"/></svg>Sessions</a>'),
    ('<rect x="14" y="14" width="7" height="7" rx="1"/></svg>Приложения</a>',
     '<rect x="14" y="14" width="7" height="7" rx="1"/></svg>Apps</a>'),
    ('<path d="M14 11a5 5 0 0 0-7-7l-3 3a5 5 0 0 0 7 7"/></svg>Подключения</a>',
     '<path d="M14 11a5 5 0 0 0-7-7l-3 3a5 5 0 0 0 7 7"/></svg>Connections</a>'),
    ('<line x1="2" y1="10" x2="22" y2="10"/></svg>Оплата</a>',
     '<line x1="2" y1="10" x2="22" y2="10"/></svg>Billing</a>'),
    ('<path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg>Уведомления</a>',
     '<path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg>Notifications</a>'),
    ('1z"/></svg>Настройки</a>',
     '1z"/></svg>Settings</a>'),
    ('        Выйти\n', '        Sign out\n'),
    ('<h1>Мой профиль</h1>', '<h1>My profile</h1>'),
    ('<div class="sub">Управляйте идентификацией и привязанными сервисами</div>',
     '<div class="sub">Manage your identity and connected services</div>'),
    ('>Редактировать</a>', '>Edit</a>'),
    ('<div class="pmeta">Участник с мая 2024 · Frankfurt, DE</div>',
     '<div class="pmeta">Member since May 2024 · Frankfurt, DE</div>'),
    ('<div class="title">Вход через Telegram</div>',
     '<div class="title">Signed in via Telegram</div>'),
    ('<div class="meta">Сегодня · 12:30</div>',
     '<div class="meta">Today · 12:30</div>'),
    ('<div class="title">Привязан TON-кошелёк</div>',
     '<div class="title">TON wallet linked</div>'),
    ('<div class="meta">Вчера · 18:12</div>',
     '<div class="meta">Yesterday · 18:12</div>'),
    ('<div class="title">Вход через web</div>',
     '<div class="title">Signed in via web</div>'),
    ('<div class="meta">Вчера · 15:40</div>',
     '<div class="meta">Yesterday · 15:40</div>'),
    ('class="pbtn-mini">Открыть</a>',
     'class="pbtn-mini">Open</a>'),
    ('<div class="dev-loc">Moscow, RU · 2 часа назад</div>',
     '<div class="dev-loc">Moscow, RU · 2 hours ago</div>'),
    ('<div class="dev-name">Двухфакторная аутентификация</div>',
     '<div class="dev-name">Two-factor authentication</div>'),
    ('<span class="badge">Включено</span>', '<span class="badge">Enabled</span>'),
    ('<div class="dev-loc">1 ключ зарегистрирован</div>',
     '<div class="dev-loc">1 key registered</div>'),
    ('<a href="#" style="font-size:12px;color:var(--primary);">Управлять</a>',
     '<a href="#" style="font-size:12px;color:var(--primary);">Manage</a>'),
    ('<h3>Подключённые аккаунты</h3>', '<h3>Connected accounts</h3>'),
    ('<span class="badge">Подключено</span>', '<span class="badge">Connected</span>'),
    ('<span class="badge">Подтверждён</span>', '<span class="badge">Verified</span>'),

    # ── about.html ──
    ('<title>О проекте — Libermall ID</title>',
     '<title>About — Libermall ID</title>'),
    ('content="Libermall ID — единая система идентификации для экосистемы Libermall. История, миссия, технологии, дорожная карта.">',
     'content="Libermall ID — the unified identity system for the Libermall ecosystem. Story, mission, technology and roadmap.">'),
    ('content="О проекте Libermall ID">',
     'content="About Libermall ID">'),
    ('content="О проекте — Libermall ID">',
     'content="About — Libermall ID">'),
    ('"name": "О проекте",', '"name": "About",'),
    ('"position": 2, "name": "О проекте", "item":',
     '"position": 2, "name": "About", "item":'),
    ('>Libermall ID решает фрагментацию аккаунтов между продуктами экосистемы Libermall. Один профиль работает везде, история переносится, не нужно регистрироваться по сто раз.</p>',
     '>Libermall ID solves account fragmentation across the Libermall ecosystem. One profile works everywhere, history carries over, and there is no need to sign up a hundred times.</p>'),
    ('<h3>🎯 Миссия</h3>', '<h3>🎯 Mission</h3>'),
    ('<p>Экосистема Libermall — это сеть взаимосвязанных продуктов: маркетплейс, биржа, виртуальные карты, каталог отзывов, AI-сервисы. Каждый работает лучше когда знает контекст пользователя — какие сайты вы оценили, какие монеты держите, какой рейтинг у вас как трейдера. До Libermall ID каждый сервис вёл свою отдельную базу аккаунтов — связи между ними рвались.</p>',
     '<p>The Libermall ecosystem is a network of connected products: a marketplace, a DEX (dex.libermall.com), virtual cards, a reviews catalog, AI services and a payment platform (pay.libermall.com). Each one works better when it knows the user context — which sites you rated, which coins you hold, your trader rating. Before Libermall ID, every service ran its own account base and the connections between them kept breaking.</p>'),
    ('<h3>⚡ Решение</h3>', '<h3>⚡ Solution</h3>'),
    ('<p>Libermall ID — один профиль, работающий везде. История переносится между продуктами. Не нужно регистрироваться по сто раз. Telegram-вход за один тап, TON Connect для криптокошельков, email magic-link для классики. Стандартный OpenID Connect — никакого vendor lock-in.</p>',
     '<p>Libermall ID — one profile that works everywhere. History carries over between products. No need to register a hundred times. One-tap Telegram sign-in, TON Connect for crypto wallets, email magic link for the classic flow. Standard OpenID Connect — no vendor lock-in.</p>'),
    ('>На чём построено</h2>', '>What it is built on</h2>'),
    ('<p>Open-source identity server (BSD 3-Clause). Поддерживает OpenID Connect, OAuth 2.0, SAML 2.0, LDAP federation. 11k+ stars на GitHub.</p>',
     '<p>Open-source identity server (BSD 3-Clause). Supports OpenID Connect, OAuth 2.0, SAML 2.0 and LDAP federation. 11k+ stars on GitHub.</p>'),
    ('<p>Профиль и сессии — Postgres, кэш и nonce — Redis. Daily backup, шифрование at-rest.</p>',
     '<p>Profile and sessions in Postgres, cache and nonce in Redis. Daily backup, encryption at rest.</p>'),
    ('<p>4096-bit ключ для подписи токенов. JWKS rotation. Token lifetime 7 дней.</p>',
     '<p>4096-bit token-signing key. JWKS rotation. Token lifetime of 7 days.</p>'),
    ('>Как это работает изнутри</h2>',
     '>How it works under the hood</h2>'),
    ('>Стандартный OAuth 2.0 / OpenID Connect flow. Кастомные адаптеры для Telegram Login Widget и TON Connect proof.</p>',
     '>Standard OAuth 2.0 / OpenID Connect flow. Custom adapters for Telegram Login Widget and TON Connect proof.</p>'),
    ('│           OAuth-клиенты (продукты)            │',
     '│            OAuth clients (products)           │'),
    ('>Дорожная карта</h2>', '>Roadmap</h2>'),
    ('>5 фаз развития от MVP до полной cross-product интеграции с tokenized identity.</p>',
     '>Five phases from MVP to full cross-product integration with tokenized identity.</p>'),
    ('<p>VPS, Casdoor, SSL, DNS, базовая инфраструктура.</p>',
     '<p>VPS, Casdoor, SSL, DNS — the base infrastructure.</p>'),
    ('<p>Telegram IdP, @LibermallIDbot, sites.reviews как первый OAuth client.</p>',
     '<p>Telegram IdP, @LibermallIDbot, sites.reviews as the first OAuth client.</p>'),
    ('<p>Landing site, brand book, Mini App, личный кабинет с управлением кошельками и сессиями.</p>',
     '<p>Landing site, brand book, Mini App, dashboard for managing wallets and sessions.</p>'),
    ('<p>Минтинг <code>@handle.lbm</code> через смарт-контракт на TON. Token economy для рейтинга экосистемы.</p>',
     '<p>Minting <code>@handle.lbm</code> via a TON smart contract. Token economy powering the ecosystem rating.</p>'),
    ('<p>Wishlists в marketplace привязаны к ID, рейтинг трейдера на DEX, накопления на Card, отзывы на Sites.Reviews — единая активность по экосистеме. Quest-система и achievements за действия в разных продуктах.</p>',
     '<p>Wishlists in the marketplace tied to your ID, trader rating on dex.libermall.com, savings on Card, reviews on Sites.Reviews — one activity layer across the whole ecosystem. Quest system and achievements for actions in different products.</p>'),
    ('<p>Криптографический паспорт по образцу <a href="https://telegram.org/blog/passport" target="_blank">Telegram Passport</a> от Pavel Durov: верифицированные документы (KYC) и биометрия под cryptographic seal. Привязывается к Libermall ID. Использовать можно везде где нужна верификация — крипто-биржи, банки, фриланс-платформы — без передачи реальных данных оператору.</p>',
     '<p>A cryptographic passport modeled after Pavel Durov\'s <a href="https://telegram.org/blog/passport" target="_blank">Telegram Passport</a>: verified documents (KYC) and biometrics under a cryptographic seal. Bound to your Libermall ID. Usable anywhere verification is required — crypto exchanges, banks, freelance platforms — without exposing the underlying data to the operator.</p>'),
    ('<h3>Libermall Mail (на TON Storage)</h3>',
     '<h3>Libermall Mail (on TON Storage)</h3>'),
    ('<p>Каждый Libermall ID получает <code>@id.libermall.com</code> email с end-to-end шифрованием по образцу Proton Mail. Метаданные и зашифрованные тела писем хранятся в распределённой сети <strong>TON Storage</strong> — никакого централизованного провайдера. Цель — превратить email из «+1 ещё одна почта» в реальный privacy-инструмент с self-custody.</p>',
     '<p>Every Libermall ID gets a <code>@id.libermall.com</code> email with end-to-end encryption à la Proton Mail. Metadata and encrypted message bodies live in the distributed <strong>TON Storage</strong> network — no centralized provider. The goal is to turn email from "yet another inbox" into a real privacy tool with self-custody.</p>'),
    ('>Всё, что мы можем — публично</h2>', '>Everything we can — public</h2>'),
    ('>Auth core — Casdoor (BSD 3-Clause). Наш UI, бот и Mini App — MIT.</p>',
     '>Auth core — Casdoor (BSD 3-Clause). Our UI, bot and Mini App — MIT.</p>'),
    ('<p>Архитектура, deploy скрипты, integration-examples.</p>',
     '<p>Architecture, deploy scripts, integration examples.</p>'),
    ('<p>Этот сайт + brand book.</p>',
     '<p>This site + brand book.</p>'),
    ('<p>Telegram бот и Mini App.</p>',
     '<p>Telegram bot and Mini App.</p>'),
    ('<h2>Вопросы, идеи, предложения?</h2>',
     '<h2>Questions, ideas, suggestions?</h2>'),
    ('<p>Команда Libermall открыта к диалогу. Пишите — отвечаем в течение суток.</p>',
     '<p>The Libermall team is open to dialogue. Email us — we reply within 24 hours.</p>'),

    # ── products.html ──
    ('<title>Продукты экосистемы — Libermall ID</title>',
     '<title>Ecosystem products — Libermall ID</title>'),
    ('content="Полный список продуктов экосистемы Libermall, которые принимают единый вход Libermall ID: Sites.Reviews, TonChat AI, TON.CEO, DEX, Card, Marketplace.">',
     'content="Full list of Libermall ecosystem products that accept Libermall ID single sign-on: Sites.Reviews, TonChat AI, TON.CEO, DEX (dex.libermall.com), Card, PayLibermall (pay.libermall.com), Marketplace.">'),
    ('content="Продукты Libermall — все принимают единый вход">',
     'content="Libermall products — all accept single sign-on">'),
    ('content="Продукты экосистемы — Libermall ID">',
     'content="Ecosystem products — Libermall ID">'),
    ('"name": "Продукты экосистемы",', '"name": "Ecosystem products",'),
    ('"position": 2, "name": "Продукты экосистемы", "item":',
     '"position": 2, "name": "Ecosystem products", "item":'),
    ('<h1>Продукты, которые принимают <span class="accent">Libermall ID</span></h1>',
     '<h1>Products that accept <span class="accent">Libermall ID</span></h1>'),
    ('<p class="lead" style="max-width:none;">Войдите через Libermall ID на любом сервисе экосистемы. История, кошельки, рейтинги — переносятся автоматически.</p>',
     '<p class="lead" style="max-width:none;">Sign in with Libermall ID on any ecosystem service. History, wallets and ratings carry over automatically.</p>'),
    ('<div class="meta">sites.reviews · 8 000+ компаний · 21 000+ отзывов</div>',
     '<div class="meta">sites.reviews · 8,000+ companies · 21,000+ reviews</div>'),
    ('<p>Каталог отзывов о сайтах и сервисах. AI-сводки плюсов и минусов, проверка безопасности доменов (SSL, blacklists, возраст), Trust Score 0-10. Browser extension и embed-widget доступны.</p>',
     '<p>A catalog of reviews for sites and services. AI summaries of pros and cons, domain safety checks (SSL, blacklists, age), Trust Score 0–10. Browser extension and embed widget available.</p>'),
    ('<div class="tags"><span class="tag">SEO</span><span class="tag">AI-сводки</span><span class="tag">Browser extension</span><span class="tag">Mini App</span></div>',
     '<div class="tags"><span class="tag">SEO</span><span class="tag">AI summaries</span><span class="tag">Browser extension</span><span class="tag">Mini App</span></div>'),
    ('class="btn btn-secondary">Открыть →</a>',
     'class="btn btn-secondary">Open →</a>'),
    ('<div class="meta">tonchat.ai · AI-помощник для TON-сообщества</div>',
     '<div class="meta">tonchat.ai · AI assistant for the TON community</div>'),
    ('<p>Чат с современными LLM (GPT, Claude, DeepSeek, Gemini), генерация изображений (DALL-E, Flux, Nano Banana), голосовые ответы (ElevenLabs). Оплата Stars, USDT или TON.</p>',
     '<p>Chat with modern LLMs (GPT, Claude, DeepSeek, Gemini), image generation (DALL-E, Flux, Nano Banana), voice replies (ElevenLabs). Pay with Stars, USDT or TON.</p>'),
    ('<div class="meta">ton.ceo · Mastodon-совместимая социальная сеть</div>',
     '<div class="meta">ton.ceo · Mastodon-compatible social network</div>'),
    ('<p>Децентрализованная соцсеть на ActivityPub для TON-сообщества. Federation с любым Mastodon-сервером. Привязка TON-кошелька, верификация через rel=me.</p>',
     '<p>A decentralized ActivityPub social network for the TON community. Federation with any Mastodon server. Link your TON wallet and verify via rel=me.</p>'),
    ('<div class="meta">dex.libermall.com · Децентрализованная биржа на TON</div>',
     '<div class="meta">dex.libermall.com · Decentralized exchange on TON</div>'),
    ('<p>Обмен Jetton-токенов на TON-блокчейне через агрегатор Omniston (Ston.fi + DeDust). Реферальная программа, виджеты, SEO-страницы для каждого токена.</p>',
     '<p>Jetton-token swaps on the TON blockchain via the Omniston aggregator (Ston.fi + DeDust). Referral program, widgets, SEO pages for every token.</p>'),
    ('<div class="meta">card.libermall.com · Виртуальные банковские карты</div>',
     '<div class="meta">card.libermall.com · Virtual bank cards</div>'),
    ('<p>Выпуск виртуальных карт с пополнением USDT, TON или USD. Расчёты в любой точке мира. Telegram Mini App для управления, привязка к TON-кошельку.</p>',
     '<p>Issue virtual cards funded with USDT, TON or USD. Spend anywhere in the world. Telegram Mini App for management, link to your TON wallet.</p>'),
    ('<div class="meta">libermall.com · Универсальный маркетплейс</div>',
     '<div class="meta">libermall.com · Universal marketplace</div>'),
    ('<p>Цифровые и физические товары, услуги, подписки. Оплата криптовалютой и фиатом. Reviews, вишлисты и quest-система привязаны к Libermall ID.</p>',
     '<p>Digital and physical goods, services and subscriptions. Pay with crypto or fiat. Reviews, wishlists and the quest system are tied to your Libermall ID.</p>'),
    ('<!-- ─── В разработке / future products ─── -->',
     '<!-- ─── In development / future products ─── -->'),
    ('<h2 class="section-title" style="margin-top:64px;margin-bottom:8px;">В разработке</h2>',
     '<h2 class="section-title" style="margin-top:64px;margin-bottom:8px;">In development</h2>'),
    ('<p style="color:var(--muted);font-size:14px;margin:0 0 24px;">Продукты, которые мы готовим к запуску. С Libermall ID они появятся с первого дня.</p>',
     '<p style="color:var(--muted);font-size:14px;margin:0 0 24px;">Products we are preparing to launch. They will support Libermall ID from day one.</p>'),
    ('<div class="meta">nft.libermall.com · NFT Marketplace на TON · <span style="color:var(--orange);">Coming soon</span></div>',
     '<div class="meta">nft.libermall.com · NFT Marketplace on TON · <span style="color:var(--orange);">Coming soon</span></div>'),
    ('<p>NFT-маркетплейс на TON-блокчейне. Минтинг, торги, royalties. Привязка к Libermall ID для верификации авторов и коллекций.</p>',
     '<p>NFT marketplace on the TON blockchain. Minting, trading, royalties. Bound to Libermall ID for verifying authors and collections.</p>'),
    ('<span class="btn btn-secondary" style="opacity:0.6;cursor:default;">В разработке</span>',
     '<span class="btn btn-secondary" style="opacity:0.6;cursor:default;">In development</span>'),
    ('<div class="meta">pay.libermall.com · Платёжная платформа</div>',
     '<div class="meta">pay.libermall.com · Payment platform</div>'),
    ('<p>Приём платежей в крипто и фиате для бизнеса. Аналог TegroMoney с интеграцией в Libermall ID и Card.</p>',
     '<p>Accept crypto and fiat payments for business. Analog to TegroMoney, integrated with Libermall ID and Card.</p>'),
    ('<div class="meta">Telegram-кошелёк на TON · <span style="color:var(--orange);">Roadmap</span></div>',
     '<div class="meta">Telegram wallet on TON · <span style="color:var(--orange);">Roadmap</span></div>'),
    ('<p>Простой крипто-кошелёк в Telegram (аналог CryptoBot, xRocket). Будет частью TON Connect. Хранение, отправка, обмен USDT и TON.</p>',
     '<p>A simple crypto wallet in Telegram (analog to CryptoBot, xRocket). Will plug into TON Connect. Hold, send and swap USDT and TON.</p>'),
    ('<span class="btn btn-secondary" style="opacity:0.6;cursor:default;">Скоро</span>',
     '<span class="btn btn-secondary" style="opacity:0.6;cursor:default;">Soon</span>'),
    ('<div class="meta">passport.libermall.com · Криптографический паспорт · <span style="color:var(--orange);">Vision</span></div>',
     '<div class="meta">passport.libermall.com · Cryptographic passport · <span style="color:var(--orange);">Vision</span></div>'),
    ('<p>Аналог Telegram Passport: верифицированная identity для KYC. Документы, биометрия, доказательство владения — всё под cryptographic seal. Опционально привязывается к Libermall ID.</p>',
     '<p>Analog to Telegram Passport: verified identity for KYC. Documents, biometrics, proof of ownership — all under a cryptographic seal. Optionally bound to your Libermall ID.</p>'),
    ('<div class="meta">@id.libermall.com · Децентрализованная почта · <span style="color:var(--orange);">Vision</span></div>',
     '<div class="meta">@id.libermall.com · Decentralized mail · <span style="color:var(--orange);">Vision</span></div>'),
    ('<p>Каждый юзер Libermall ID получает <code>@id.libermall.com</code> email. End-to-end encryption по образцу Proton.me, хранение на <code>.ton</code>-сторадже (TON Storage).</p>',
     '<p>Every Libermall ID user gets a <code>@id.libermall.com</code> email. End-to-end encryption à la Proton.me, storage on <code>.ton</code> (TON Storage).</p>'),
    ('<div class="meta">tegro.finance · TegroMoney · Tegro Card · партнёр</div>',
     '<div class="meta">tegro.finance · TegroMoney · Tegro Card · partner</div>'),
    ('<p>Tegro Finance DEX, TegroMoney платёжная платформа, и Tegro Card — партнёрский набор продуктов. Интеграция с Libermall ID для cross-product identity.</p>',
     '<p>Tegro Finance DEX, TegroMoney payment platform, and Tegro Card — a partner product set. Integrated with Libermall ID for cross-product identity.</p>'),
    ('<h2>Ваш сервис тоже может принимать Libermall ID</h2>',
     '<h2>Your service can accept Libermall ID too</h2>'),
    ('<p>Стандартный OpenID Connect, готовые SDK, 5 минут до интеграции.</p>',
     '<p>Standard OpenID Connect, ready-made SDKs, 5 minutes to integrate.</p>'),

    # ── legal-dpa.html ──
    ('content="DPA для enterprise-клиентов Libermall ID. GDPR-compliant обработка данных.">',
     'content="DPA for Libermall ID enterprise customers. GDPR-compliant data processing.">'),
    ('<p class="article-lead">Эффективен с 2026-05-24. Версия 1.0. Заключается с enterprise-клиентами в дополнение к Terms of Service.</p>',
     '<p class="article-lead">Effective 2026-05-24. Version 1.0. Signed with enterprise customers in addition to the Terms of Service.</p>'),
    ('<p><strong>Контроллер:</strong> Клиент (компания, использующая Libermall ID для своих пользователей).<br>',
     '<p><strong>Controller:</strong> Customer (the company using Libermall ID for its end users).<br>'),
    ('<strong>Процессор:</strong> Libermall (оператор Libermall ID).</p>',
     '<strong>Processor:</strong> Libermall (operator of Libermall ID).</p>'),
    ('<li>Идентификаторы пользователей (Telegram ID, TON wallet, email)</li>',
     '<li>User identifiers (Telegram ID, TON wallet, email)</li>'),
    ('<li>Профильные данные (имя, аватар, language)</li>',
     '<li>Profile data (name, avatar, language)</li>'),
    ('<li>Сессии и audit log</li>',
     '<li>Sessions and audit log</li>'),
    ('<h2>3. Цель обработки</h2>', '<h2>3. Purpose of processing</h2>'),
    ('<p>Предоставление сервиса единой аутентификации согласно <a href="/terms.html">Terms of Service</a> и инструкциям Контроллера.</p>',
     '<p>Providing the single sign-on service according to the <a href="/terms.html">Terms of Service</a> and Controller instructions.</p>'),
    ('<h2>4. Категории субъектов</h2>', '<h2>4. Categories of data subjects</h2>'),
    ('<p>Конечные пользователи Контроллера, использующие Libermall ID для входа в сервисы Контроллера.</p>',
     '<p>End users of the Controller who use Libermall ID to sign in to the Controller\'s services.</p>'),
    ('<p>Libermall использует следующих sub-processors:</p>',
     '<p>Libermall uses the following sub-processors:</p>'),
    ('<li><strong>Cloudflare</strong> — DNS, CDN, DDoS защита</li>',
     '<li><strong>Cloudflare</strong> — DNS, CDN, DDoS protection</li>'),
    ('<li><strong>Let\'s Encrypt</strong> — SSL сертификаты</li>',
     '<li><strong>Let\'s Encrypt</strong> — SSL certificates</li>'),
    ('<li><strong>GitHub</strong> — хранение исходного кода (не данных)</li>',
     '<li><strong>GitHub</strong> — source code hosting (no user data)</li>'),
    ('<p>При добавлении новых sub-processors Контроллер уведомляется за 30 дней.</p>',
     '<p>The Controller is notified 30 days in advance when new sub-processors are added.</p>'),
    ('<h2>6. Меры безопасности</h2>', '<h2>6. Security measures</h2>'),
    ('<li>Access control (RBAC, 2FA для admins)</li>',
     '<li>Access control (RBAC, 2FA for admins)</li>'),
    ('<li>Daily backups с шифрованием</li>',
     '<li>Daily backups with encryption</li>'),
    ('<li>Audit log с 12-month retention</li>',
     '<li>Audit log with 12-month retention</li>'),
    ('<h2>7. Передача данных</h2>', '<h2>7. Data transfers</h2>'),
    ('<p>Все данные хранятся в EU (Frankfurt, DE). Передача за пределы EU не осуществляется.</p>',
     '<p>All data is stored in the EU (Frankfurt, DE). No transfers outside the EU.</p>'),
    ('<h2>8. Права субъектов</h2>', '<h2>8. Data subject rights</h2>'),
    ('<p>По запросу Контроллера в течение 30 дней Libermall:</p>',
     '<p>Upon Controller request, within 30 days Libermall:</p>'),
    ('<li>Экспортирует данные субъекта (GDPR Article 15)</li>',
     '<li>Exports subject data (GDPR Article 15)</li>'),
    ('<li>Исправляет неточные данные (Article 16)</li>',
     '<li>Corrects inaccurate data (Article 16)</li>'),
    ('<li>Удаляет данные (Article 17)</li>',
     '<li>Deletes data (Article 17)</li>'),
    ('<li>Передаёт данные в machine-readable формате (Article 20)</li>',
     '<li>Transmits data in a machine-readable format (Article 20)</li>'),
    ('<h2>9. Утечки данных</h2>', '<h2>9. Data breaches</h2>'),
    ('<p>В случае data breach Libermall уведомляет Контроллера в течение 24 часов и предоставляет:</p>',
     '<p>In case of a data breach Libermall notifies the Controller within 24 hours and provides:</p>'),
    ('<li>Описание характера утечки</li>', '<li>Description of the breach</li>'),
    ('<li>Категории и количество затронутых субъектов</li>',
     '<li>Categories and number of affected subjects</li>'),
    ('<li>Принятые и планируемые меры</li>',
     '<li>Measures taken and planned</li>'),
    ('<li>Контакт DPO для дополнительных запросов</li>',
     '<li>DPO contact for follow-up requests</li>'),
    ('<h2>10. Аудит</h2>', '<h2>10. Audit</h2>'),
    ('<p>Enterprise-клиенты имеют право на ежегодный аудит обработки данных, согласованный заранее. Альтернатива — независимые аудит-отчёты (SOC 2 Type 1 — Q4 2026, ISO 27001 — 2027).</p>',
     '<p>Enterprise customers have the right to an annual data-processing audit, scheduled in advance. Alternative: independent audit reports (SOC 2 Type 1 — Q4 2026, ISO 27001 — 2027).</p>'),
    ('<h2>11. Прекращение</h2>', '<h2>11. Termination</h2>'),
    ('<p>При прекращении сотрудничества Libermall в течение 30 дней либо удаляет данные, либо возвращает их Контроллеру в зависимости от выбора Контроллера.</p>',
     '<p>On termination Libermall either deletes or returns the data to the Controller within 30 days, at the Controller\'s choice.</p>'),
    ('<h2>12. Контакт</h2>', '<h2>12. Contact</h2>'),
    ('<p style="margin-top:48px;color:var(--muted);font-size:13px;">Для подписи DPA: <a href="mailto:legal@libermall.com">legal@libermall.com</a></p>',
     '<p style="margin-top:48px;color:var(--muted);font-size:13px;">To sign a DPA: <a href="mailto:legal@libermall.com">legal@libermall.com</a></p>'),

    # ── legal-sla.html ──
    ('content="Service Level Agreement Libermall ID для enterprise-клиентов. 99.9% uptime, credit-back policy.">',
     'content="Libermall ID Service Level Agreement for enterprise customers. 99.9% uptime, credit-back policy.">'),
    ('<p class="article-lead">Эффективен с 2026-05-24. Версия 1.0. Применяется к Enterprise-плану.</p>',
     '<p class="article-lead">Effective 2026-05-24. Version 1.0. Applies to the Enterprise plan.</p>'),
    ('<tr><th>План</th><th>Uptime guarantee</th><th>Response time</th></tr>',
     '<tr><th>Plan</th><th>Uptime guarantee</th><th>Response time</th></tr>'),
    ('<h2>2. Что считается downtime</h2>', '<h2>2. What counts as downtime</h2>'),
    ('<p>Downtime = период когда хотя бы один из критичных endpoint\'ов недоступен или возвращает 5xx-ошибку более 1 минуты подряд:</p>',
     '<p>Downtime = a period when at least one critical endpoint is unavailable or returns a 5xx error for more than 1 consecutive minute:</p>'),
    ('<h2>3. Что НЕ считается downtime</h2>', '<h2>3. What does NOT count as downtime</h2>'),
    ('<li>Плановое обслуживание (с уведомлением за 7 дней)</li>',
     '<li>Scheduled maintenance (announced 7 days in advance)</li>'),
    ('<li>Сбои на стороне клиента (неправильные redirect URIs, expired secrets и т.д.)</li>',
     '<li>Client-side issues (wrong redirect URIs, expired secrets, etc.)</li>'),
    ('<li>Force majeure (DDoS &gt;500 Gbps, государственные блокировки, аварии магистральных провайдеров)</li>',
     '<li>Force majeure (DDoS &gt;500 Gbps, government blocks, upstream provider outages)</li>'),
    ('<li>Время restore после уведомлённой аварии 3rd-party (Telegram API, Cloudflare и т.д.)</li>',
     '<li>Restore time after a notified 3rd-party outage (Telegram API, Cloudflare, etc.)</li>'),
    ('<p>Если месячный uptime ниже гарантированного — credit back на следующий месяц:</p>',
     '<p>If monthly uptime falls below the guarantee — credit back on the next month:</p>'),
    ('<tr><th>Месячный uptime</th><th>Credit (% от месячного платежа)</th></tr>',
     '<tr><th>Monthly uptime</th><th>Credit (% of monthly fee)</th></tr>'),
    ('<tr><td>&lt; 90.0%</td><td>100% + право расторжения без штрафа</td></tr>',
     '<tr><td>&lt; 90.0%</td><td>100% + right to terminate without penalty</td></tr>'),
    ('<h2>5. Запрос credit\'а</h2>', '<h2>5. Requesting a credit</h2>'),
    ('<p>Запрос подаётся в течение 30 дней после месяца с нарушением. Контакт: <a href="mailto:sla@libermall.com">sla@libermall.com</a> с указанием:</p>',
     '<p>Submit a request within 30 days after the month of the breach. Contact: <a href="mailto:sla@libermall.com">sla@libermall.com</a> with:</p>'),
    ('<li>Период недоступности</li>', '<li>Period of unavailability</li>'),
    ('<li>Затронутые endpoints</li>', '<li>Affected endpoints</li>'),
    ('<li>Логи / скриншоты ошибок</li>',
     '<li>Logs / error screenshots</li>'),
    ('<p>Решение принимается в течение 14 дней. Credit применяется к следующему биллинговому циклу.</p>',
     '<p>A decision is made within 14 days. The credit is applied to the next billing cycle.</p>'),
    ('<h2>6. Поддержка</h2>', '<h2>6. Support</h2>'),
    ('<tr><th>Severity</th><th>Описание</th><th>Response time</th></tr>',
     '<tr><th>Severity</th><th>Description</th><th>Response time</th></tr>'),
    ('<tr><td>P0 Critical</td><td>Полный outage</td><td>1 час 24/7</td></tr>',
     '<tr><td>P0 Critical</td><td>Full outage</td><td>1 hour 24/7</td></tr>'),
    ('<tr><td>P1 High</td><td>Значительная деградация</td><td>4 часа</td></tr>',
     '<tr><td>P1 High</td><td>Significant degradation</td><td>4 hours</td></tr>'),
    ('<tr><td>P2 Medium</td><td>Минорная функциональность сломана</td><td>1 business day</td></tr>',
     '<tr><td>P2 Medium</td><td>Minor functionality broken</td><td>1 business day</td></tr>'),
    ('<tr><td>P3 Low</td><td>Question / feature request</td><td>3 рабочих дня</td></tr>',
     '<tr><td>P3 Low</td><td>Question / feature request</td><td>3 business days</td></tr>'),
    ('<h2>7. Каналы коммуникации</h2>', '<h2>7. Communication channels</h2>'),
    ('<p style="margin-top:48px;color:var(--muted);font-size:13px;">SLA включён в стандартный Enterprise-контракт. Контакт: <a href="mailto:legal@libermall.com">legal@libermall.com</a></p>',
     '<p style="margin-top:48px;color:var(--muted);font-size:13px;">SLA is included in the standard Enterprise contract. Contact: <a href="mailto:legal@libermall.com">legal@libermall.com</a></p>'),

    # ── privacy.html ──
    ('<title>Политика конфиденциальности — Libermall ID</title>',
     '<title>Privacy Policy — Libermall ID</title>'),
    ('content="Политика конфиденциальности Libermall ID: какие данные собираем, как храним, кому передаём.">',
     'content="Libermall ID Privacy Policy: what data we collect, how we store it, who we share it with.">'),
    ('content="Политика конфиденциальности — Libermall ID">',
     'content="Privacy Policy — Libermall ID">'),
    ('<p class="article-lead">Effective date: 2026-05-24. Версия 1.0.</p>',
     '<p class="article-lead">Effective date: 2026-05-24. Version 1.0.</p>'),
    ('>Сколько храним</a>', '>How long we keep it</a>'),
    ('>Ваши права</a>', '>Your rights</a>'),
    ('>Изменения</a>', '>Changes</a>'),
    ('<p>Libermall ID — сервис единой идентификации, оператор экосистемы Libermall. Контакт по вопросам приватности: <a href="mailto:privacy@libermall.com">privacy@libermall.com</a>.</p>',
     '<p>Libermall ID — a unified identity service, operator of the Libermall ecosystem. Privacy contact: <a href="mailto:privacy@libermall.com">privacy@libermall.com</a>.</p>'),
    ('<h2 id="what">Какие данные мы собираем</h2>',
     '<h2 id="what">What data we collect</h2>'),
    ('<li><strong>Идентификаторы:</strong> Telegram user ID, TON wallet address (если привязан), email (если указан), Apple ID, Google ID</li>',
     '<li><strong>Identifiers:</strong> Telegram user ID, TON wallet address (if linked), email (if provided), Apple ID, Google ID</li>'),
    ('<li><strong>Профиль:</strong> имя, фамилия, аватар (из Telegram Login Widget или social-провайдеров)</li>',
     '<li><strong>Profile:</strong> first name, last name, avatar (from Telegram Login Widget or social providers)</li>'),
    ('<li><strong>Сессии и активность:</strong> время входа, IP-адрес для rate-limit, история привязки/отвязки сервисов</li>',
     '<li><strong>Sessions and activity:</strong> sign-in time, IP address for rate limiting, history of linking/unlinking services</li>'),
    ('<li><strong>Согласия:</strong> для каких сервисов экосистемы вы дали согласие на передачу данных</li>',
     '<li><strong>Consents:</strong> which ecosystem services you have granted data sharing to</li>'),
    ('<li>Аутентифицировать вас и держать сессию активной</li>',
     '<li>Authenticate you and keep your session active</li>'),
    ('<li>Передавать вашему согласованному сервису-клиенту минимально необходимые данные</li>',
     '<li>Pass the minimum required data to the service you have authorized</li>'),
    ('<li>Защищать аккаунт от взлома (rate-limit, anomaly detection)</li>',
     '<li>Protect your account from compromise (rate limiting, anomaly detection)</li>'),
    ('<li>Обеспечивать законные требования (например, log-retention)</li>',
     '<li>Meet legal requirements (e.g. log retention)</li>'),
    ('<h2 id="sharing">Кому мы передаём данные</h2>',
     '<h2 id="sharing">Who we share data with</h2>'),
    ('<p>Только тем сервисам экосистемы Libermall, которым вы явно дали согласие через OAuth consent screen. Передаются только claims, соответствующие запрошенным scopes (например, <code>email</code> только если вы согласились на scope <code>email</code>).</p>',
     '<p>Only with Libermall ecosystem services you have explicitly authorized via an OAuth consent screen. Only claims matching the requested scopes are shared (e.g. <code>email</code> only if you granted the <code>email</code> scope).</p>'),
    ('<p>Третьим сторонам мы не передаём данные, кроме случаев требований закона.</p>',
     '<p>We do not share data with third parties except where required by law.</p>'),
    ('<h2 id="retention">Сколько мы храним</h2>',
     '<h2 id="retention">How long we keep it</h2>'),
    ('<li>Аккаунт — пока не удалён вами</li>',
     '<li>Your account — until you delete it</li>'),
    ('<li>Audit log входов — 12 месяцев</li>',
     '<li>Sign-in audit log — 12 months</li>'),
    ('<li>Привязанные кошельки — пока не отвязаны</li>',
     '<li>Linked wallets — until you unlink them</li>'),
    ('<li>Резервные копии БД — 14 дней rolling backup</li>',
     '<li>Database backups — 14-day rolling backup</li>'),
    ('<h2 id="rights">Ваши права</h2>', '<h2 id="rights">Your rights</h2>'),
    ('<li>Запросить экспорт всех данных о вас (GDPR Article 15)</li>',
     '<li>Request an export of all data about you (GDPR Article 15)</li>'),
    ('<li>Исправить неточные данные</li>',
     '<li>Correct inaccurate data</li>'),
    ('<li>Удалить аккаунт и связанные данные (right to be forgotten)</li>',
     '<li>Delete your account and related data (right to be forgotten)</li>'),
    ('<li>Отозвать согласие для конкретного сервиса</li>',
     '<li>Revoke consent for a specific service</li>'),
    ('<p>Любой запрос — <a href="mailto:privacy@libermall.com">privacy@libermall.com</a>, ответим в течение 30 дней.</p>',
     '<p>Any request — <a href="mailto:privacy@libermall.com">privacy@libermall.com</a>, we will respond within 30 days.</p>'),
    ('<p>Мы используем только функциональные cookies для поддержания сессии. Аналитики или трекинга третьих сторон на id.libermall.com нет.</p>',
     '<p>We use only functional cookies to keep your session alive. No analytics or third-party tracking on id.libermall.com.</p>'),
    ('<li>JWT-токены подписаны RS256 (4096-bit ключ)</li>',
     '<li>JWT tokens signed with RS256 (4096-bit key)</li>'),
    ('<li>Пароли (если есть) — bcrypt + salt</li>',
     '<li>Passwords (if any) — bcrypt + salt</li>'),
    ('<li>2FA через TOTP и WebAuthn (passkeys)</li>',
     '<li>2FA via TOTP and WebAuthn (passkeys)</li>'),
    ('<li>Изолированный VPS, открытые только 22/80/443</li>',
     '<li>Isolated VPS, only ports 22/80/443 open</li>'),
    ('<h2 id="changes">Изменения</h2>', '<h2 id="changes">Changes</h2>'),
    ('<p>Все изменения публикуются на этой странице с обновлением даты. Существенные изменения — уведомление по email/Telegram.</p>',
     '<p>All changes are posted on this page with an updated date. Material changes — notification via email/Telegram.</p>'),
    ('<p style="margin-top:48px;color:var(--muted);font-size:13px;">Вопросы: <a href="mailto:privacy@libermall.com">privacy@libermall.com</a></p>',
     '<p style="margin-top:48px;color:var(--muted);font-size:13px;">Questions: <a href="mailto:privacy@libermall.com">privacy@libermall.com</a></p>'),

    # ── terms.html ──
    ('<title>Условия использования — Libermall ID</title>',
     '<title>Terms of Service — Libermall ID</title>'),
    ('content="Условия использования сервиса Libermall ID.">',
     'content="Libermall ID Terms of Service.">'),
    ('content="Условия использования — Libermall ID">',
     'content="Terms of Service — Libermall ID">'),
    ('<p class="article-lead">Effective date: 2026-05-24. Версия 1.0.</p>',
     '<p class="article-lead">Effective date: 2026-05-24. Version 1.0.</p>'),
    ('<h2>1. Принятие условий</h2>', '<h2>1. Acceptance of terms</h2>'),
    ('<p>Используя Libermall ID, вы соглашаетесь с этими условиями. Если не согласны — не пользуйтесь сервисом.</p>',
     '<p>By using Libermall ID you agree to these terms. If you do not agree — do not use the service.</p>'),
    ('<h2>2. Описание сервиса</h2>', '<h2>2. Service description</h2>'),
    ('<p>Libermall ID — бесплатная служба единой аутентификации (Single Sign-On) для продуктов экосистемы Libermall и интегрированных третьих сторон. Технологическая основа — OpenID Connect / OAuth 2.0 / SAML 2.0.</p>',
     '<p>Libermall ID is a free Single Sign-On service for Libermall ecosystem products and integrated third parties. The technology stack: OpenID Connect / OAuth 2.0 / SAML 2.0.</p>'),
    ('<h2>3. Регистрация и аккаунт</h2>',
     '<h2>3. Registration and account</h2>'),
    ('<li>Вы можете зарегистрироваться через Telegram Login, TON Connect, email, Apple ID или Google</li>',
     '<li>You can register via Telegram Login, TON Connect, email, Apple ID or Google</li>'),
    ('<li>Вы обязуетесь предоставлять достоверные данные</li>',
     '<li>You agree to provide accurate information</li>'),
    ('<li>Вы несёте ответственность за безопасность своего Telegram-аккаунта / TON-кошелька / email — компрометация даёт доступ к Libermall ID</li>',
     '<li>You are responsible for the security of your Telegram account / TON wallet / email — compromise grants access to your Libermall ID</li>'),
    ('<li>Один человек — один аккаунт. Создание дублей запрещено</li>',
     '<li>One person — one account. Duplicate accounts are prohibited</li>'),
    ('<h2>4. Запрещено</h2>', '<h2>4. Prohibited</h2>'),
    ('<li>Использовать сервис для незаконной деятельности</li>',
     '<li>Using the service for illegal activity</li>'),
    ('<li>Создавать ботов / fake аккаунты</li>',
     '<li>Creating bots / fake accounts</li>'),
    ('<li>Атаковать инфраструктуру (DDoS, brute-force, exploit)</li>',
     '<li>Attacking the infrastructure (DDoS, brute-force, exploits)</li>'),
    ('<li>Обходить rate-limit и другие защитные меры</li>',
     '<li>Bypassing rate limits and other protective measures</li>'),
    ('<li>Распространять чужие данные, полученные через Libermall ID</li>',
     '<li>Distributing other users\' data obtained via Libermall ID</li>'),
    ('<h2>5. Сторонние сервисы</h2>', '<h2>5. Third-party services</h2>'),
    ('<p>Libermall ID позволяет логиниться в сервисы экосистемы и third-party приложениях. Мы не отвечаем за их действия, контент или политики приватности. Перед подтверждением OAuth consent — проверьте, какие данные передаются.</p>',
     '<p>Libermall ID lets you sign in to ecosystem services and third-party apps. We are not responsible for their actions, content or privacy policies. Before approving an OAuth consent, review what data is being shared.</p>'),
    ('<h2>6. Доступность сервиса</h2>', '<h2>6. Service availability</h2>'),
    ('<p>Сервис предоставляется «как есть». Мы стремимся к 99.9% uptime, но не гарантируем непрерывной работы. Плановые работы и аварии возможны — мы оповещаем заранее когда возможно.</p>',
     '<p>The service is provided "as is". We aim for 99.9% uptime but do not guarantee uninterrupted operation. Scheduled maintenance and outages are possible — we announce them in advance when feasible.</p>'),
    ('<h2>7. Прекращение доступа</h2>', '<h2>7. Termination</h2>'),
    ('<p>Мы можем заблокировать аккаунт при нарушении этих условий. Вы можете удалить аккаунт в любой момент — через личный кабинет или письмом на <a href="mailto:privacy@libermall.com">privacy@libermall.com</a>.</p>',
     '<p>We may suspend your account if you violate these terms. You can delete your account at any time — through the dashboard or by emailing <a href="mailto:privacy@libermall.com">privacy@libermall.com</a>.</p>'),
    ('<h2>8. Изменения условий</h2>', '<h2>8. Changes to the terms</h2>'),
    ('<p>При существенных изменениях — уведомление за 30 дней. Минорные правки публикуются с обновлением даты.</p>',
     '<p>For material changes — 30 days\' notice. Minor edits are published with an updated date.</p>'),
    ('<h2>9. Ответственность</h2>', '<h2>9. Liability</h2>'),
    ('<p>Libermall ID не несёт ответственности за косвенные убытки, потерянную выгоду, ущерб репутации, связанный с использованием сервиса в максимальных пределах разрешённых законом.</p>',
     '<p>Libermall ID is not liable for indirect damages, lost profits or reputational harm arising from use of the service, to the maximum extent permitted by law.</p>'),
    ('<h2>10. Юрисдикция</h2>', '<h2>10. Jurisdiction</h2>'),
    ('<p>Применимое право — законодательство юрисдикции оператора (Libermall). Споры разрешаются в соответствии с применимым правом.</p>',
     '<p>Applicable law — the law of the operator\'s jurisdiction (Libermall). Disputes are resolved under the applicable law.</p>'),
    ('<p style="margin-top:48px;color:var(--muted);font-size:13px;">Вопросы по условиям: <a href="mailto:legal@libermall.com">legal@libermall.com</a></p>',
     '<p style="margin-top:48px;color:var(--muted);font-size:13px;">Questions about the terms: <a href="mailto:legal@libermall.com">legal@libermall.com</a></p>'),

    # ── footer "Компания" (appears in many files) ──
    ('<h4>Компания</h4>', '<h4>Company</h4>'),
]
